Repository tronprotocol/java-tron, pull requests merged in 2023-12, with the labels that each got.

#5602 docs(protobuf): change transaction data structure description
  Tron protobuf protocol document.md
Labels: area:docs

#5606 Minor grammar fixes to the README file
  README.md
Labels: topic: Documentation, area:docs

#5632 docs(md): remove redundant descriptions
  README.md
  docs/implement-a-customized-actuator-en.md
  docs/implement-a-customized-actuator-zh.md
  quickstart.md
  run.md
Labels: area:docs

#5631 docs(README): update the description of signature verification
  README.md
Labels: area:docs

#5601 feat(api): print more details for unexpected error
  framework/src/main/java/org/tron/core/services/http/Util.java
Labels: topic:Log

#5603 test(plugins/dbLite): add test for merge function
  plugins/src/test/java/org/tron/plugins/DbLiteTest.java
Labels: area:test

#5624 feat(log/api): separate unexpected and expected logs
  framework/src/main/java/org/tron/core/services/RpcApiService.java
Labels: topic:Log
