Repository tronprotocol/java-tron, pull requests merged in 2024-01, with the labels that each got.

#5647 feat(lite): upgrade DbLite tool
  plugins/src/main/java/org/tron/plugins/DbLite.java
Labels: area:db

#5406 feat(db): optimize old rewards withdrawal
  actuator/src/main/java/org/tron/core/utils/ProposalUtil.java
  chainbase/src/main/java/org/tron/core/db/common/iterator/DBIterator.java
  chainbase/src/main/java/org/tron/core/db/common/iterator/RockStoreIterator.java
  chainbase/src/main/java/org/tron/core/db/common/iterator/StoreIterator.java
  chainbase/src/main/java/org/tron/core/service/MortgageService.java
  chainbase/src/main/java/org/tron/core/service/RewardViCalService.java
  chainbase/src/main/java/org/tron/core/store/DynamicPropertiesStore.java
  chainbase/src/main/java/org/tron/core/store/RewardViStore.java
  common/src/main/java/org/tron/common/parameter/CommonParameter.java
  common/src/main/java/org/tron/common/prometheus/MetricKeys.java
  common/src/main/java/org/tron/common/prometheus/MetricsHistogram.java
  common/src/main/java/org/tron/core/Constant.java
  common/src/main/java/org/tron/core/config/Parameter.java
  framework/src/main/java/org/tron/core/Wallet.java
  framework/src/main/java/org/tron/core/config/args/Args.java
  framework/src/main/java/org/tron/core/consensus/ProposalService.java
  framework/src/main/java/org/tron/core/db/common/iterator/AbstractIterator.java
  framework/src/main/java/org/tron/core/db/common/iterator/AssetIssueIterator.java
  framework/src/main/java/org/tron/core/db/common/iterator/DBIterator.java
  framework/src/main/java/org/tron/core/db/common/iterator/TransactionIterator.java
  framework/src/main/java/org/tron/core/db/common/iterator/WitnessIterator.java
  framework/src/test/java/org/tron/core/db/DBIteratorTest.java
  framework/src/test/java/org/tron/core/services/ComputeRewardTest.java
  framework/src/test/java/org/tron/core/services/ProposalServiceTest.java
Labels: Improvement, status: on-going

#5650 feat(LiteFullNode): remove LiteFullNodeTool
  framework/build.gradle
  framework/src/main/java/org/tron/tool/litefullnode/DbTool.java
  framework/src/main/java/org/tron/tool/litefullnode/LiteFullNodeTool.java
  framework/src/main/java/org/tron/tool/litefullnode/README.md
  framework/src/main/java/org/tron/tool/litefullnode/Util.java
  framework/src/main/java/org/tron/tool/litefullnode/db/DBInterface.java
  framework/src/main/java/org/tron/tool/litefullnode/db/LevelDBImpl.java
  framework/src/main/java/org/tron/tool/litefullnode/db/RocksDBImpl.java
  framework/src/main/java/org/tron/tool/litefullnode/iterator/DBIterator.java
  framework/src/main/java/org/tron/tool/litefullnode/iterator/LevelDBIterator.java
  framework/src/main/java/org/tron/tool/litefullnode/iterator/RockDBIterator.java
  framework/src/test/java/org/tron/core/actuator/ActuatorFactoryTest.java
  framework/src/test/java/org/tron/core/db/AccountTraceStoreTest.java
  framework/src/test/java/org/tron/core/db/BlockIndexStoreTest.java
  framework/src/test/java/org/tron/core/db/BlockStoreTest.java
  framework/src/test/java/org/tron/core/db/DelegatedResourceStoreTest.java
  framework/src/test/java/org/tron/core/db/DelegationStoreTest.java
  framework/src/test/java/org/tron/core/db/ExchangeStoreTest.java
  framework/src/test/java/org/tron/core/db/ExchangeV2StoreTest.java
  framework/src/test/java/org/tron/core/db/MarketAccountStoreTest.java
  framework/src/test/java/org/tron/core/db/MarketOrderStoreTest.java
  framework/src/test/java/org/tron/core/db/RecentBlockStoreTest.java
  framework/src/test/java/org/tron/core/db/RecentTransactionStoreTest.java
  framework/src/test/java/org/tron/core/db/TransactionHistoryTest.java
  framework/src/test/java/org/tron/core/db/ZKProofStoreTest.java
  framework/src/test/java/org/tron/core/services/http/ClearABIServletTest.java
  framework/src/test/java/org/tron/core/services/http/CreateAccountServletTest.java
  framework/src/test/java/org/tron/core/services/http/CreateAssetIssueServletTest.java
  framework/src/test/java/org/tron/core/services/http/CreateSpendAuthSigServletTest.java
  framework/src/test/java/org/tron/core/services/http/CreateWitnessServletTest.java
  framework/src/test/java/org/tron/core/services/http/GetAccountByIdServletTest.java
  framework/src/test/java/org/tron/core/services/http/GetBlockByIdServletTest.java
  framework/src/test/java/org/tron/core/services/http/GetBlockByNumServletTest.java
  framework/src/test/java/org/tron/core/services/http/GetTransactionInfoByBlockNumServletTest.java
  framework/src/test/java/org/tron/core/services/http/GetTransactionInfoByIdServletTest.java
  framework/src/test/java/org/tron/core/services/http/GetTransactionListFromPendingServletTest.java
  framework/src/test/java/org/tron/core/services/http/UpdateAccountServletTest.java
  framework/src/test/java/org/tron/program/LiteFullNodeToolTest.java
  plugins/README.md
Labels: area:db

#5697 feat(log): remove unused log for getnodeinfo api
  framework/src/main/java/org/tron/core/db/Manager.java
  framework/src/main/java/org/tron/core/services/NodeInfoService.java
Labels: topic:Log
